version: '3.8'

services:
  db:
    image: postgres:13
    container_name: hyperhire_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hyperhire-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperhire_app
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - INFURA_API_KEY=${INFURA_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - POLYGONSCAN_API_KEY=${POLYGONSCAN_API_KEY}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - hyperhire-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  hyperhire-network:
    driver: bridge